export const services = {
  gateways: ['customers', 'admins', 'clients'],
  services: [
    'app',
    'app-stats',
    'auth',
    'billing',
    'configs',
    'currencies',
    'customers',
    'emails',
    'events-manager',
    'functions',
    'groups',
    'leaderboards',
    'messaging',
    'notifications',
    'payments',
    'players',
    'profiles',
    'shops',
    'stats',
  ],
};
